[package]
name = "shutterctl"
version = "0.1.0"
authors = ["Martin Leuner <martin.leuner@rwth-aachen.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
